---
# configure the worker servers

- name: Create Unit file - owlcrawler-extractor
  template: src=unit-extractor.j2 dest=/usr/lib/systemd/system/owlcrawler-extractor.service owner=root group=root mode=0644
  notify: Enable workers
