---
# configure the worker servers

- name: Create Unit file - owlcrawler-fetcher
  template: src=unit-fetcher.j2 dest=/usr/lib/systemd/system/owlcrawler-fetcher.service owner=root group=root mode=0644
  notify: Enable workers
