---
# extract worker servers

#To collect ip on etcd server to use on unit file for extractor
- hosts: etcdservers
  name: Gather facts from collectors
  tasks: [ ]

- hosts: extractservers
  sudo: yes
  vars_files:
    - vars/production.yml
  roles:
    - common
    - extractor
    - go
