---
# fetch worker servers

#To collect ip on etcd server to use on unit file for fetcher
- hosts: natsdservers
  name: Gather facts from collectors
  tasks: [ ]

- hosts: fetchservers
  sudo: yes
  vars_files:
    - vars/production.yml
  roles:
    - common
    - common-worker
    - go
    - fetcher
