---
# configure the worker servers

- name: Create user to run workers as
  user: name=owlcrawler shell=/bin/false group=owlcrawler

- name: Create worker directory
  file: path=/srv/owlcrawler-worker owner=owlcrawler group=ops mode=2770 state=directory

- name: Copy nats credentials file
  template: src=gnatsd.json.j2 dest=/home/owlcrawler/.gnatsd.json owner=owlcrawler group=root mode=0600
